Cross validation is the technique which allows you to evaluate the model performance

K Fold Cross Validation:

K-Fold Cross Validation is a technique used in machine learning to assess how well a model generalizes to unseen data. It divides the data into K subsets (or "folds"). Here’s how it works:

Data Splitting: The dataset is randomly split into K equal-sized folds.

Model Training and Testing: For each fold:

->Use K-1 folds for training the model.

->Use the remaining fold for testing (validation).

->This process is repeated K times, each time using a different fold for validation.

->Average Performance: The model's performance is averaged across all K trials to give a more reliable estimate of its generalization ability.


In [14]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_digits
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
digits = load_digits()

In [8]:
kf = KFold(n_splits = 3)  #n_splits...number of folds
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [10]:
#function that calcultaes model score
def get_score(model, X_train, X_test, Y_train, Y_test):
    model.fit(X_train, Y_train)
    return model.score(X_test, Y_test)

In [12]:
from sklearn.model_selection import StratifiedKFold   #stratifiedKFold classifies the data uniformly
folds = StratifiedKFold(n_splits = 3)

In [15]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, Y_train, Y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, Y_train, Y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, Y_train, Y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, Y_train, Y_test))

In [16]:
scores_logistic   #scores of logistic regression in 3 splits/folds

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [17]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [18]:
scores_rf

[0.9298831385642737, 0.9398998330550918, 0.9398998330550918]

In [23]:
#we can perform above operations in a simpler way using cross_val_score function.
#Note**: cross_val_score uses stratifield kfold by default

from sklearn.model_selection import cross_val_score

In [20]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [21]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [22]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92320534, 0.95158598, 0.91819699])

Parameter tunning using k fold cross validation

In [24]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8686933581626318

In [28]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9404376163873369

In [26]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9404500310366231

In [27]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9443140906269398

Here we used cross_val_score to fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result.